Stepik chapter two
Eddie55d/Learn-Go pull request #2
Opened 2023-05-02 17:56 UTC by Eddie55d

stepik-chapter-two

2023-05-02 18:04 UTC, ALarutin commented on Stepik/Chapter2/task-2-1-2.go
> +	nums := []int{}
Можно создавать slic-ы сразу с нужный объемом выделенной памяти для них, это более производительно
там вообще есть кроме этого ещё 2 способа создать slice через make
```golang
nums := make([]int, 4)

for i := 0; i < len(nums); i++ {
 nums[i] = number
}

nums := make([]int, 0, 4)

for i := 0; i < len(nums); i++ {
 nums = append(nums, number)
}
```

в-первом случае, создается массив с 4 элементами, дефолтных значений, в нашем случае 4 нуля, и мы можем их перезаписывать,
во-втором массив пустой, но у него выделено памяти под 4 элемента, перезаписывать мы не можем ничего, потому что будем обращаться в пустым ячейкам и словим панику, но можем в него добавлять через append
за количество элементов отвечает len(), а за выделенных объем cap()

2023-05-02 18:07 UTC, ALarutin commented on Stepik/Chapter2/task-2-1-3.go
> +		total = 0
Можно было сразу сделать `return 0`, а в другом cas-е `return 1`

2023-05-02 18:08 UTC, ALarutin commented on Stepik/Chapter2/task-2-3-1.go
> +	fmt.Printf("%d", *x1**x2)
Всегда работай с указателями аккуратно, если попробовать разименовать указать `*x1`, который будет равен nil, случится паника

2023-05-02 18:09 UTC, ALarutin commented on Stepik/Chapter2/task-2-4-1.go
> +	case s.On == false:
Не пиши `== false`, упрощай через ! -> `case !s.On:~

2023-05-06 11:22 UTC, RusPatrick requested changes

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-1-3.go
> +	for _, v := range nums {
сделай все в первом цикле, без нужды не надо проходить по одному и тому же массиву несколько раз если можно обойтись одним проходом

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-4-1.go
> +	case s.Ammo != 0 && s.On != false:
просто `s.On`

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-1.go
> +	rs := []rune{}
Строки можно переводить в руны просто написав `[]rune(text)`

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-2.go
> +	}
Очень сложное решение, можно проще, подумай еще)

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-1-4.go
> +	return idx
подумай еще над задачей, кажется ты делаешь много лишних действий

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-3.go
> +	fmt.Println(strings.Index(string(str), string(subStr)))
Хорошо что ты знаешь о функции strings.Index, но напиши решение без нее.

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-5.go
> +	fmt.Println(strings.Join(str4, ""))
Сложное и неочевидное решение, попробуй упростить

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-5.go
> +	fmt.Println(strings.Join(str4, ""))
Если ты хочешь массив сток состоящих из одной буквы объединить в одну строку, то ты можешь хранить буквы `[]rune` и чтоб переветси руны в строку можно сделать 
```go
runes := []rune{}
fmt.Println(string(runes)) 
```

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-6.go
> +		if strings.Contains(string(charSet), string(v)) == true {
Bool значения не надо проверять через `==`
Используй просто 
```go
if strings.Contains(string(charSet), string(v)) {
    ...
}
```

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-6.go
> +		} else {
ты можешь опустить else, если в блоке if происходит break, return или continue
```go
if strings.Contains(string(charSet), string(v)) { 
   continue
}
correct = false
```

А еще можешь сделать вот так
```go
if !strings.Contains(string(charSet), string(v)) { 
   correct = false
}
```

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-6-1.go
> +	if a == 0 || b == 0 {
если `a` равна нулю, то ошибки не будет

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-7-2.go
> +		panic("строка больше 1000 символов")
Хорошо что ты знаешь о паниках, но лучше их не использовать

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-7-2.go
> +	fmt.Println(strings.Join(formatStr, "*"))
При итерации по строке через `range` во втором значении, то есть в `v` будет лежать `rune`
То есть ты можешь сделать `formatStr `типом `[]rune` и когда захочешь напечатать строку можно будет сделать fmt.Println(string(formatStr))

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-7-3.go
> +	}
Лишние действия, тебе не нужен []string{} 
Попробуй переделать

2023-05-06 11:22 UTC, RusPatrick commented on Stepik/Chapter2/task-2-7-4.go
> +	if lenStr > 1000 {
нет такого условия)

2023-05-07 13:05 UTC, Eddie55d commented on Stepik/Chapter2/task-2-1-3.go
> +		total = 0
тогда выдаёт missing return

2023-05-07 15:30 UTC, RusPatrick commented on Stepik/Chapter2/task-2-1-3.go
> +		}
```go
if v == 0 {
   count1++
   continue
}
count2++
```

2023-05-07 16:08 UTC, RusPatrick requested changes

2023-05-07 16:08 UTC, RusPatrick commented on Stepik/Chapter2/task-2-1-3.go
> +	}
```go
if count1>count2 {
   return 0 
}
return 1
```

2023-05-07 16:08 UTC, RusPatrick commented on Stepik/Chapter2/task-2-4-1.go
> +	}
```go
if !s.On {
    return false
}

if s.Ammo == 0 {
    return false
}

s.Ammo--
return true
```

2023-05-07 16:08 UTC, RusPatrick commented on Stepik/Chapter2/task-2-5-2.go
> +	}
```go
str2 := make([]rune, 0, len(utf8.RuneCountInString(str))

for _, v := range str {
   str2 = append(str2, v)
}

if strings.EqualFold(str, string(str2)) {
   return "Палиндром"
}

return "Нет"
```

2023-05-07 16:08 UTC, RusPatrick commented on Stepik/Chapter2/task-2-6-1.go
> +	}
```
_, err := fmt.Scan(&a, &b)
if err != nil {
   fmt.Println(err)
   return
}

if b == 0 {
   fmt.Println("ошибка")
   return
}

fmt.Printf("%d", a/b)
```

2023-05-28 17:11 UTC, merged